//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Moves = new HashSet<Move>();
        }
    
        public int GameId { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Site { get; set; }
        public string Round { get; set; }
        public string WhiteName { get; set; }
        public string BlackName { get; set; }
        public Nullable<short> WhiteElo { get; set; }
        public Nullable<short> BlackElo { get; set; }
        public byte Result { get; set; }
        public byte ResultReason { get; set; }
        public short MoveCount { get; set; }
        public string ECO { get; set; }
        public string PGN { get; set; }
        public string Event { get; set; }
        public string PgnHash { get; set; }
        public string GameHash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Move> Moves { get; set; }
    }
}
