//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public int GameId { get; set; }
        public int FromPositionId { get; set; }
        public int ToPositionId { get; set; }
        public byte FromFile { get; set; }
        public byte FromRank { get; set; }
        public byte ToRank { get; set; }
        public short PlyNumber { get; set; }
        public byte ToFile { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Position FromPosition { get; set; }
        public virtual Position ToPosition { get; set; }
    }
}
