//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.MovesFromHere = new HashSet<Move>();
            this.MovesToHere = new HashSet<Move>();
            this.Squares = new HashSet<Square>();
        }
    
        public int PositionId { get; set; }
        public string FEN { get; set; }
        public short MoveNumber { get; set; }
        public bool WhiteToMove { get; set; }
        public Nullable<byte> EnPassantFile { get; set; }
        public bool CanWhiteCastleKingSide { get; set; }
        public bool CanWhiteCastleQueenSide { get; set; }
        public bool CanBlackCastleKingSide { get; set; }
        public bool CanBlackCastleQueenSide { get; set; }
        public byte PlysTo50 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Move> MovesFromHere { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Move> MovesToHere { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Square> Squares { get; set; }
    }
}
